from martinho0330/ubuntu:22.04
MAINTAINER Martin_Ho
RUN apt update; apt install nginx curl -y; exit 0
COPY hello-plain-text.conf /etc/nginx/conf.d/hello-plain-text.conf
COPY nginx.conf /etc/nginx/nginx.conf
ENTRYPOINT ["nginx", "-g", "daemon off;"]